// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.scheduler;

import com.jobplatform.scheduler.entity.Job;
import com.jobplatform.scheduler.repository.JobRepository;
import com.jobplatform.scheduler.worker.WorkerManager;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import java.util.List;

@Component
public class JobSchedulerEngine {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(JobSchedulerEngine.class);
    private final JobRepository jobRepository;
    private final WorkerManager workerManager;

    @Scheduled(fixedRate = 2000)
    public void pollPendingJobs() {
        // Simplified polling approach for the prototype: find all PENDING jobs
        List<Job> pendingJobs = jobRepository.findAll().stream().filter(job -> "PENDING".equals(job.getStatus())).toList();
        for (Job job : pendingJobs) {
            log.info("Claiming job: {}", job.getId());
            job.setStatus("IN_PROGRESS");
            jobRepository.save(job);
            // Dispatch to Virtual Thread worker pool
            workerManager.executeJob(job);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public JobSchedulerEngine(final JobRepository jobRepository, final WorkerManager workerManager) {
        this.jobRepository = jobRepository;
        this.workerManager = workerManager;
    }
}
