// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "dead_letter_queue")
public class DeadLetterQueue extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "job_id")
    private Job job;
    private String failureReason;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Job getJob() {
        return this.job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFailureReason() {
        return this.failureReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJob(final Job job) {
        this.job = job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFailureReason(final String failureReason) {
        this.failureReason = failureReason;
    }
}
