// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "jobs")
public class Job extends BaseEntity {
    private String name;
    private String payload;
    private String status;
    @ManyToOne
    @JoinColumn(name = "queue_id")
    private Queue queue;
    @ManyToOne
    @JoinColumn(name = "retry_policy_id")
    private RetryPolicy retryPolicy;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPayload() {
        return this.payload;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Queue getQueue() {
        return this.queue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RetryPolicy getRetryPolicy() {
        return this.retryPolicy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPayload(final String payload) {
        this.payload = payload;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQueue(final Queue queue) {
        this.queue = queue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRetryPolicy(final RetryPolicy retryPolicy) {
        this.retryPolicy = retryPolicy;
    }
}
