// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "job_executions")
public class JobExecution extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "job_id")
    private Job job;
    @ManyToOne
    @JoinColumn(name = "worker_id")
    private Worker worker;
    private String status;
    private LocalDateTime startedAt;
    private LocalDateTime completedAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Job getJob() {
        return this.job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Worker getWorker() {
        return this.worker;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getStartedAt() {
        return this.startedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCompletedAt() {
        return this.completedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJob(final Job job) {
        this.job = job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorker(final Worker worker) {
        this.worker = worker;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartedAt(final LocalDateTime startedAt) {
        this.startedAt = startedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompletedAt(final LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }
}
