// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "job_logs")
public class JobLog extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "job_execution_id")
    private JobExecution jobExecution;
    private String logMessage;
    private String level;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public JobExecution getJobExecution() {
        return this.jobExecution;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogMessage() {
        return this.logMessage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLevel() {
        return this.level;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJobExecution(final JobExecution jobExecution) {
        this.jobExecution = jobExecution;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogMessage(final String logMessage) {
        this.logMessage = logMessage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLevel(final String level) {
        this.level = level;
    }
}
