// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "projects")
public class Project extends BaseEntity {
    private String name;
    @ManyToOne
    @JoinColumn(name = "org_id")
    private Organization organization;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Organization getOrganization() {
        return this.organization;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrganization(final Organization organization) {
        this.organization = organization;
    }
}
