// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "queues")
public class Queue extends BaseEntity {
    private String name;
    private String type;
    private Integer concurrency;
    @ManyToOne
    @JoinColumn(name = "project_id")
    private Project project;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getConcurrency() {
        return this.concurrency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Project getProject() {
        return this.project;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setConcurrency(final Integer concurrency) {
        this.concurrency = concurrency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProject(final Project project) {
        this.project = project;
    }
}
