// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "retry_policies")
public class RetryPolicy extends BaseEntity {
    private String name;
    private String strategy;
    private Integer maxRetries;
    private Integer backoffMultiplier;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStrategy() {
        return this.strategy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getMaxRetries() {
        return this.maxRetries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getBackoffMultiplier() {
        return this.backoffMultiplier;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStrategy(final String strategy) {
        this.strategy = strategy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaxRetries(final Integer maxRetries) {
        this.maxRetries = maxRetries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBackoffMultiplier(final Integer backoffMultiplier) {
        this.backoffMultiplier = backoffMultiplier;
    }
}
