// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "scheduled_jobs")
public class ScheduledJob extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "job_id")
    private Job job;
    private String cronExpression;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Job getJob() {
        return this.job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCronExpression() {
        return this.cronExpression;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJob(final Job job) {
        this.job = job;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCronExpression(final String cronExpression) {
        this.cronExpression = cronExpression;
    }
}
