// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "workers")
public class Worker extends BaseEntity {
    private String hostname;
    private String status;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHostname() {
        return this.hostname;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHostname(final String hostname) {
        this.hostname = hostname;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }
}
