// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "worker_heartbeats")
public class WorkerHeartbeat extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "worker_id")
    private Worker worker;
    private LocalDateTime lastSeen;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Worker getWorker() {
        return this.worker;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getLastSeen() {
        return this.lastSeen;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorker(final Worker worker) {
        this.worker = worker;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastSeen(final LocalDateTime lastSeen) {
        this.lastSeen = lastSeen;
    }
}
