// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.service;

import com.jobplatform.scheduler.entity.Queue;
import com.jobplatform.scheduler.repository.QueueRepository;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class QueueService {
    private final QueueRepository queueRepository;

    public Queue createQueue(Queue queue) {
        return queueRepository.save(queue);
    }

    public List<Queue> getAllQueues() {
        return queueRepository.findAll();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QueueService(final QueueRepository queueRepository) {
        this.queueRepository = queueRepository;
    }
}
