// Generated by delombok at Fri Jul 03 17:15:59 IST 2026
package com.jobplatform.scheduler.controller;

import com.jobplatform.scheduler.entity.Queue;
import com.jobplatform.scheduler.service.QueueService;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/queues")
public class QueueController {
    private final QueueService queueService;

    @PostMapping
    public Queue createQueue(@RequestBody Queue queue) {
        return queueService.createQueue(queue);
    }

    @GetMapping
    public List<Queue> getQueues() {
        return queueService.getAllQueues();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public QueueController(final QueueService queueService) {
        this.queueService = queueService;
    }
}
